[default]
# Don't check text that matches the following regexes'
extend-ignore-re = [
    '\\cite\{.*\}', # citations contain arbitrary keys,
    '@cite \w'
]

[default.extend-identifiers]
# Don't correct these whole identifiers (word-groups)
bungartz2016precice = "bungartz2016precice"
chourdakis2021precice = "chourdakis2021precice"
y_FoR = "y_FoR"
use_degress = "use_degress"
MPI_MODE_WRONLY = "MPI_MODE_WRONLY"
Equil = "Equil"
multline = "multline"

[default.extend-words]
# Don't correct these word (parts)
OCE = "OCE"
MIS = "MIS"
parm = "parm"
nd = "nd"
inout = "inout"
datas = "datas"
Elemente = "Elemente"
Methode = "Methode"
workd = "workd"
Stoer = "Stoer"
Lik = "Lik"
htmp = "htmp"
Numer = "Numer"
ue = "ue"
reord = "reord"
Uite = "Uite"
strat = "strat"
Ned = "Ned"
BA = "BA"
Fike = "Fike"
clen = "clen"

# Don't check the following files
[files]
extend-exclude = [
    "*.output",
    "tests/parameter_handler/parameter_handler_25.cc", # this file contains a typo on purpose
    "*.svg",
    "*.pvsm",
    "*.vtu",
    "*.bib", # bib entries contain many arbitrary abbreviations
    ] 
